/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Varun' at '3/12/18 12:13 PM' with Gradle 3.0
 *
 * @author Varun, @date 3/12/18 12:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
